  
name: Build RedPill DSM loader New

on: workflow_dispatch

jobs:
  redpill:
    runs-on: ubuntu-latest
    name: Build RedPill lkm and load
    steps:
      - uses: actions/checkout@v2.1.0
        name: checkout src
        id: checkout
        with:
          submodules: 'true'
      - name: Build DS918+ 7.0.1
        id: build-ds918-701
        run: |
            bash build-ds918-7.0.1new.sh
      - name: Archive DS918+ 7.0.1 loader image
        uses: actions/upload-artifact@v2
        with:
          name: redpill-DS918+_7.0.1-loader
          path: output/redpill-DS918+_7.0.1*.img
